// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/arcs": {
            "get": {
                "description": "delivers Arcs from OPT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "arcs"
                ],
                "summary": "fetches Arcs from OPT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Arc"
                            }
                        }
                    }
                }
            }
        },
        "/api/chapters/id/{selectedChapter}": {
            "post": {
                "description": "downloads chapter from OPT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "downloads chapter from OPT",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Selected Chapter",
                        "name": "selectedChapter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "should download local",
                        "name": "local",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "should send to telegram chat",
                        "name": "telegram",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.SavedDirectory"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Get server health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "description": "Saved settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "saved settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                }
            },
            "post": {
                "description": "Save your settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "saves settings",
                "parameters": [
                    {
                        "description": "Settings to save",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                }
            }
        },
        "/api/settings/id/{settingsId}": {
            "put": {
                "description": "Updates your settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "updates settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Updated Settings",
                        "name": "settingsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings to update",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.SavedDirectory": {
            "type": "object",
            "properties": {
                "chapterName": {
                    "type": "string"
                },
                "chapterNumber": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "models.Arc": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OPTEntry"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.OPTEntry": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_available": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                }
            }
        },
        "models.Settings": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "telegramChatId": {
                    "type": "string"
                },
                "telegramToken": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Web Opt Mangadownloader API",
	Description:      "This is a web api server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
